"""empty message

Revision ID: 10cccc9ec67c
Revises: 7dae97d2fa04
Create Date: 2019-06-07 22:03:03.657928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10cccc9ec67c'
down_revision = '7dae97d2fa04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('choices', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'choices')
    # ### end Alembic commands ###
